/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class appleduckit_shirabe_engine_platformlayer_android_graphics_gpu_api_GpuApiInterface */

#ifndef _Included_appleduckit_shirabe_engine_platformlayer_android_graphics_gpu_api_GpuApiInterface
#define _Included_appleduckit_shirabe_engine_platformlayer_android_graphics_gpu_api_GpuApiInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     appleduckit_shirabe_engine_platformlayer_android_graphics_gpu_api_GpuApiInterface
 * Method:    initGpuAPI
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_appleduckit_shirabe_engine_platformlayer_android_graphics_gpu_1api_GpuApiInterface_initGpuAPI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
